// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbcZ7Tyhk24glJ2Qs3ywKiY1jC57vZ2Vo',
    appId: '1:517866791350:web:29c5884444c0002e38a117',
    messagingSenderId: '517866791350',
    projectId: 'premens',
    authDomain: 'premens.firebaseapp.com',
    databaseURL: 'https://premens-default-rtdb.firebaseio.com',
    storageBucket: 'premens.appspot.com',
    measurementId: 'G-GSXE0TMYFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWbZKE1-EktRKfSa_7z-atya46evNo1xo',
    appId: '1:517866791350:android:e52d8e2657f6a65838a117',
    messagingSenderId: '517866791350',
    projectId: 'premens',
    databaseURL: 'https://premens-default-rtdb.firebaseio.com',
    storageBucket: 'premens.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_A58bZXjyg8VxKquYP9sJ59Md4NR3eI',
    appId: '1:517866791350:ios:f440da2a315b308238a117',
    messagingSenderId: '517866791350',
    projectId: 'premens',
    databaseURL: 'https://premens-default-rtdb.firebaseio.com',
    storageBucket: 'premens.appspot.com',
    iosClientId: '517866791350-7ij2uq64fj1835e4q6kuijv2gqdksfu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.premens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6_A58bZXjyg8VxKquYP9sJ59Md4NR3eI',
    appId: '1:517866791350:ios:f440da2a315b308238a117',
    messagingSenderId: '517866791350',
    projectId: 'premens',
    databaseURL: 'https://premens-default-rtdb.firebaseio.com',
    storageBucket: 'premens.appspot.com',
    iosClientId: '517866791350-7ij2uq64fj1835e4q6kuijv2gqdksfu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.premens',
  );
}
